# Generated by Django 5.1.15 on 2026-09-24 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_education_level_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('assignment_new', 'Tugas baru'), ('material_new', 'Materi baru'), ('submission_graded', 'Jawaban dinilai'), ('session_scheduled', 'Sesi diskusi dijadwalkan'), ('session_cancelled', 'Sesi diskusi dibatalkan'), ('deadline_soon', 'Tenggat dekat'), ('submissions_new', 'Pengumpulan baru'), ('students_joined', 'Mahasiswa bergabung')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=300)),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.CharField(blank=True, default='', max_length=120)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.profile')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_recipient_recent_idx'), models.Index(fields=['recipient', 'group_key'], name='notif_recipient_group_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'deadline_soon')), fields=('recipient', 'group_key'), name='notif_deadline_once')],
            },
        ),
    ]
