# Generated by Django 5.1.15 on 2026-06-15 03:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=80)),
                ('education_level', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA-SMK', 'SMA/SMK')], max_length=16)),
                ('join_code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.profile')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('expected_bloom_level', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('education_level', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA-SMK', 'SMA/SMK')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.class')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('revision_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.profile')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='ReasoningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('revision', 'Revision'), ('paste', 'Paste'), ('submitted', 'Submitted')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasoning_events', to='academics.submission')),
            ],
            options={
                'db_table': 'reasoning_events',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_band', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=8)),
                ('bloom_level', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='academics.submission')),
            ],
            options={
                'db_table': 'analysis_results',
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['owner', '-created_at'], name='classes_owner_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_ref', '-created_at'], name='assign_class_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', '-submitted_at'], name='sub_assign_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student_profile', '-submitted_at'], name='sub_student_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningevent',
            index=models.Index(fields=['submission', 'occurred_at'], name='reason_sub_time_idx'),
        ),
    ]
