# Generated by Django 5.1.15 on 2026-07-15 01:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0002_profile_password_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='confidence',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academics.class')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='core.profile')),
            ],
            options={
                'db_table': 'class_memberships',
                'constraints': [models.UniqueConstraint(fields=('class_ref', 'student_profile'), name='membership_unique_per_class')],
            },
        ),
    ]
