# Generated by Django 5.1.15 on 2026-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_reset_dict_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_source',
            field=models.CharField(choices=[('llm', 'LLM'), ('heuristic', 'Heuristic'), ('seed', 'Seed demo')], default='heuristic', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='bloom_confidence',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='signal_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
