# Generated by Django 5.1.15 on 2026-08-05 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_education_level_mahasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='education_level',
        ),
        migrations.AddField(
            model_name='class',
            name='program_studi',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
