# Generated by Django 5.1.15 on 2026-08-11 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_class_prodi_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Dijadwalkan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('can_explain', 'Dapat menjelaskan'), ('partial', 'Sebagian dapat dijelaskan'), ('cannot_explain', 'Belum dapat menjelaskan'), ('inconclusive', 'Belum dapat disimpulkan')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='academics.submission')),
            ],
            options={
                'db_table': 'verbal_verifications',
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='verif_status_time_idx')],
            },
        ),
    ]
