# Generated by Django 5.1.15 on 2026-08-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_verbal_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningevent',
            name='event_type',
            field=models.CharField(choices=[('started', 'Started'), ('revision', 'Revision'), ('paste', 'Paste'), ('submitted', 'Submitted'), ('progress', 'Progress')], max_length=16),
        ),
    ]
