# Generated by Django 5.1.15 on 2026-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_reasoningevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_source',
            field=models.CharField(choices=[('llm', 'LLM'), ('heuristic', 'Heuristic'), ('seed', 'Seed demo'), ('detector', 'External detector')], default='heuristic', max_length=16),
        ),
    ]
