# Generated by Django 5.1.15 on 2026-08-15 19:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_analysisresult_analysis_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_hash', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model_version', models.CharField(max_length=16)),
                ('language', models.CharField(max_length=8)),
                ('ai_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reliable', models.BooleanField()),
                ('attack_kinds', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detector_scores',
                'constraints': [models.UniqueConstraint(fields=('text_hash', 'provider', 'model_version', 'language'), name='detector_score_unique_key')],
            },
        ),
    ]
