# Generated by Django 5.1.15 on 2026-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_detectorscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='import_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='origin',
            field=models.CharField(choices=[('typed', 'Diketik'), ('document_import', 'Diimpor dari dokumen')], default='typed', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='rich_content',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
