# Generated by Django 5.1.15 on 2026-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=16)),
                ('education_level', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA-SMK', 'SMA/SMK')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
