# Generated by Django 5.1.15 on 2026-09-25 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_education_level_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('given', 'Diberikan'), ('updated', 'Diperbarui'), ('withdrawn', 'Ditarik')], max_length=16)),
                ('policy_version', models.CharField(max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.profile')),
            ],
            options={
                'db_table': 'consent_records',
                'indexes': [models.Index(fields=['profile', '-created_at'], name='consent_profile_recent_idx')],
            },
        ),
    ]
